### ISSUE TITLE
Apt package release

### ISSUE THREAD

**Issue by mmurooka** [jrl-umi3218/mc_state_observation#20]
It would be great if an apt package of this repository could be released.

Some features of this repository (especially AttitudeObserver) are becoming almost indispensable for the mc_rtc controller. I would like to install and use AttitudeObserver via apt when doing dynamics simulation in CI of some mc_rtc controllers.

**Comment by gergondet** [comment]
Hi @mmurooka 

mc_state_observation is now available as two packages:
- `mc-state-observation` contains the non ROS-based observers (atm Attitude only)
- `ros-${ROS_DISTRO}-mc-state-observation` contains the ROS-based observers (all others atm)

It's already available in the head repository and coming to the stable repository following the release of mc_rtc v1.14.0

**Comment by mmurooka** [comment]
@gergondet Thank you!
